version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "4321:4321"
    volumes:
      - ./frontend:/src/app
    links:
      - backend
    command: >
      sh -c "npm install && npm run dev"
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/src/app
    links:
      - db
  db:
    image: postgres:12-bullseye
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: db